sudo: false

language: node_js

services:
  - mongodb

node_js:
  - "4"
  - "5"
  - "6"
  - "stable"

before_install:
  - "node -v"
  - "npm -v"
  - "mongo --version"
  - "mkdir var/logs var/cache"
  - "chmod -R 777 var/logs var/cache"